steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        europe-west3-docker.pkg.dev/docai-accelerator/cloud-functions-source-deploy/image-handler:version_1
      - '-f'
      - ../cloud_functions/image_handler/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        europe-west3-docker.pkg.dev/docai-accelerator/cloud-functions-source-deploy/image-handler:version_1
timeout: 3600s
images:
  - >-
    europe-west3-docker.pkg.dev/docai-accelerator/cloud-functions-source-deploy/image-handler:version_1