steps:
  - id: "build-docker-image"
    timeout: 3600s
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_REPO_REGION}.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/&{_IMAGE_NAME}:&{_IMAGE_TAG}", "../cloud_functions/image_handler/Dockerfile"]
  - id: "push-docker-image"
    timeout: 3600s
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REPO_REGION}.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/&{_IMAGE_NAME}:&{_IMAGE_TAG}"]
    waitFor: ["build-docker-image"]